### PR TITLE
feat: Additional pipeline API for text payloads, response_type, response_schema

### PR DESCRIPTION
**Pull request by asymness**
Resolves https://github.com/Unstructured-IO/community/issues/32

**Summary of Changes**
- [x] Implemented a `text-input` pipeline at [{{ cookiecutter.repo_name }}/pipeline-notebooks/pipeline-text-input.ipynb](https://github.com/Unstructured-IO/pipeline-template/compare/main...asymness:pipeline-template:feat-text-input-pipeline?expand=1#diff-0b39ccf8d5ab6d0a16a500a8a454ad191eade64bcbc363dc67b7203275da5927)
- [x] Add support for `output_schema` and `output_format` in the generated APIs.
- [x] The generated API responds with the contents of the specified file(s).
- [x] Ensure maximum test coverage of generated FastAPI routes. (Some lines can't be covered since the API is generated from a template and some lines are unreachable in this specific case of pipeline APIs)

### CODE REVIEW

**Review by cragwolfe — COMMENTED** [review]
Basically looks good and the tests pass (after working around the missing module mentioned below). However, please see below points mainly around user friendliness below (esp., first time users).

* The two test_docs are quite large, can we add two smaller docs instead? (say less than 10K) 

* Let's rename the notebooks `pipeline-process-text.ipynb` and `pipeline-process-file.ipynb` so it's obvious what the difference is.

* Let's add the `filename` param `pipeline_api` in (the renamed)`pipeline-process-file.ipynb` to show the capability.

* Update the return string in pipeline_api to include the filename, file_content_type, and file size.

* The README inside the generated repo should be updated to indicate there are now two sample pipeline notebooks, i.e. here:
https://github.com/Unstructured-IO/pipeline-template/blob/main/%7B%7B%20cookiecutter.repo_name%20%7D%7D/README.md?plain=1#L20 .

* When attempting to run the tests via `make test` for a generated template, I ran into the issue: `ModuleNotFoundError: No module named 'requests'`. Please add this requirement to `https://github.com/Unstructured-IO/pipeline-template/blob/main/%7B%7B%20cookiecutter.repo_name%20%7D%7D/requirements/test.in

* When I do `make generate-api` in a freshly generated pipeline dir and using a fresh virtualenv (having done `make pip-compile`, `make pip-install`), I see diffs in the import order. Though, this may actually be a bug with unstructured-api-tools, not sure there is anything to do there. This is with`unstructured-api-tools==0.4.6`.

**Comment by asymness** [comment]
@cragwolfe I've made the requested changes.
- [x] Replaced test docs with simple text files less than than 10KB.
- [x] Renamed notebooks as specified.
- [x] Added `filename` parameter in the renamed notebook.
- [x] Updated the return string to return `<filename>:<file content type>:<file size>`.
- [x] Updated the `README` to include description about sample notebooks.
- [x] Fixed the missing module issue. With the latest version of `FastAPI` that is in `unstructured-api-tools==0.4.7`, the FastAPI test client uses `httpx` instead of `requests` which is added to `test.in` file.
- [x] Removed `*.txt` files from `requirements` directory.
- [x] Ensured no diff in import order when using `unstructured-api-tools==0.4.7`.

**Comment by cragwolfe** [comment]
@asymness , this is looking good. i believe the only item remaining from my previous comment is:

* When attempting to run the tests via make test for a generated template, I ran into the issue: ModuleNotFoundError: No module named 'requests'. Please add this requirement to `https://github.com/Unstructured-IO/pipeline-template/blob/main/%7B%7B%20cookiecutter.repo_name%20%7D%7D/requirements/test.in

**Comment by cragwolfe** [comment]
The changes in this PR appear to be included in https://github.com/Unstructured-IO/pipeline-template/pull/7 . Closing.

**Pull request closed without merging**
